mybatis:
  # 配置mapper的扫描，找到所有的mapper.xml的映射文件
  mapperLocations: classpath:mybatis/**/*Mapper.xml
  configLocation: classpath:mybatis/mybatis-config.xml


spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/home?useUnicode=true&characterEncoding=utf-8
    username: root
    password:
  jpa:
    showSql: true
    hibernate:
      ddlAuto:update